blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /


blogger_admin:
    resource: "@BloggerAdminBundle/Controller"
    prefix:   /admin
    type: annotation

app:
    resource: @AppBundle/Controller/
    type:     annotation
