# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    methods: [GET]


BloggerBlogBundle_about:
    pattern: /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    methods: [GET]

BloggerBlogBundle_contactShow:
    pattern: /contact
    defaults: { _controller: BloggerBlogBundle:Page:contactShow}
    methods: [GET]

BloggerBlogBundle_contactPost:
    pattern: /contact
    defaults: { _controller: BloggerBlogBundle:Page:contactPost}
    methods: [POST]
