<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    public function getCommentsForBlog($blogId, $approved = true) {

        $qb =  $this->createQueryBuilder('c')
                    ->select('c')
                    ->where('c.blog = :blogId')
                    ->addOrderBy('c.created')
                    ->setParameter('blogId',$blogId);

        if(!is_null($approved)) {
            $qb->andWhere('c.approved = :approved')
                ->setParameter('approved',$approved);
        }

        return $qb->getQuery()
                    ->getResult();
    }
}
